### ISSUE TITLE
Move from cncf.io/calendar to community.cncf.io

### ISSUE THREAD

**Issue by scottrigby** [open-gitops/project#57]
The [shared CNCF calendar](http://cncf.io/calendar) has become difficult to scale and maintain. They are encouraging projects to move to the [community groups space](https://community.cncf.io/).

I've spoken with Amye and Chris A about it and offered to help us (and a few other projects I'm involved with) switch over.

## To-do

- [ ] Move zoom meetings to Bevy
    - [ ] set up GWG space on CNCF community site
- ~Move text chats from https://github.com/gitops-working-group/gitops-working-group/tree/main/meetings to a Google drive, for greater flexibility (as @chris-short noted we could also store zoom meeting video downloads there too).~ 
    These are being moved to git in https://github.com/cncf/tag-app-delivery/pull/150
- [x] remove https://github.com/gitops-working-group/gitops-working-group/blob/main/MEETINGS.md in favor of the Google doc, which more people can edit without PRs for this every week ⏳  https://github.com/gitops-working-group/gitops-working-group/pull/163
- [ ] import old meetings into CNCF community site (whether we also do videos into Bevy is something we can look into if it's possible / worth it)

## 📊  Poll

Should moving meetings to CNCF community site / Bevy be the ceremonial event where we move to an OpenGitOps space there? Where we start having OpenGitOps biweekly meetings?
